### GET Categories
GET https://localhost:3000/api/

### POST Categories
POST https://localhost:3000/api/
Content-Type: application/json

### GET Products
GET https://localhost:3000/api/

### POST Products
POST https://localhost:3000/api/
Content-Type: application/json
